services:
  fromthepage:
    # build:
    #   dockerfile: Containerfile
    #   context: .
    image: docker.io/bencomp/fromthepage-passenger:latest
    platform: "linux/amd64"
    env_file: ./local.env
    environment:
    - PASSENGER_APP_ENV=production
    depends_on:
    - "mysql"
    - "elasticsearch"
    ports:
    - "8080:80"
    volumes:
      - fromthepage_logs:/home/app/fromthepage/log
      - fromthepage_tmp:/home/app/fromthepage/tmp
      - fromthepage_public_images_working:/home/app/fromthepage/public/images/working
      - fromthepage_public_images_uploaded:/home/app/fromthepage/public/images/uploaded
      - fromthepage_public_uploads:/home/app/fromthepage/public/uploads
      - fromthepage_public_text:/home/app/fromthepage/public/text
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    platform: "linux/amd64"
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_USER=fromthepage
    - MYSQL_PASSWORD=fromthepage
    - MYSQL_DATABASE=fromthepage
    volumes:
    - fromthepage_mysql_data:/var/lib/mysql
    - ./data:/docker-entrypoint-initdb.d
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    platform: "linux/amd64"
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - bootstrap.memory_lock=true
    volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"
    - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

volumes:
  fromthepage_mysql_data:
  fromthepage_logs:
  fromthepage_tmp:
  fromthepage_public_images_working:
  fromthepage_public_images_uploaded:
  fromthepage_public_uploads:
  fromthepage_public_text:
  elasticsearch_data: 